Regenerate debian/tests/

diff --git a/debian/tests/cgi b/debian/tests/cgi
--- a/debian/tests/cgi
+++ b/debian/tests/cgi
@@ -3,16 +3,16 @@ set -e
 
 # Author: Robie Basak <robie.basak@ubuntu.com>
 
-# /etc/apache2/conf-available/php7.0-cgi.conf should exist. If this is renamed
-# to /etc/apache2/conf-available/php7.0-cgi in the future, then this test needs
+# /etc/apache2/conf-available/php5.6-cgi.conf should exist. If this is renamed
+# to /etc/apache2/conf-available/php5.6-cgi in the future, then this test needs
 # to be updated.
 
-if [ ! -f /etc/apache2/conf-available/php7.0-cgi.conf ]; then
-    echo "/etc/apache2/conf-available/php7.0-cgi.conf not found" >&2
+if [ ! -f /etc/apache2/conf-available/php5.6-cgi.conf ]; then
+    echo "/etc/apache2/conf-available/php5.6-cgi.conf not found" >&2
     exit 1
 fi
 
-echo "Action application/x-httpd-php /cgi-bin/php7.0" >> /etc/apache2/conf-available/php7.0-cgi.conf
+echo "Action application/x-httpd-php /cgi-bin/php5.6" >> /etc/apache2/conf-available/php5.6-cgi.conf
 
 cat > /var/www/html/hello.php <<EOT
 <?php echo "Hello, world!\n"; ?>
@@ -20,11 +20,11 @@ EOT
 
 # Make sure that any mod_php mechanism is disabled, since we want to get CGI
 # mode here.
-a2dismod php7.0 2>/dev/null || true
+a2dismod php5.6 2>/dev/null || true
 
 a2enmod actions
 a2enmod cgi 2>/dev/null
-a2enconf php7.0-cgi
+a2enconf php5.6-cgi
 service apache2 restart 2>/dev/null
 result=`wget -O- http://localhost/hello.php 2>/dev/null`
 test "$result" = "Hello, world!"
