Prepare packaging for PHP 7.1

diff --git a/debian/tests/fpm b/debian/tests/fpm
--- a/debian/tests/fpm
+++ b/debian/tests/fpm
@@ -4,10 +4,10 @@ set -e
 # PHP-FPM test based on mod-php test
 # Author: Neal Gompa <ngompa13@gmail.com>
 
-# /etc/apache2/conf-available/php7.0-fpm.conf should exist.
+# /etc/apache2/conf-available/php7.1-fpm.conf should exist.
 
-if [ ! -f /etc/apache2/conf-available/php7.0-fpm.conf ]; then
-    echo "/etc/apache2/conf-available/php7.0-fpm.conf not found" >&2
+if [ ! -f /etc/apache2/conf-available/php7.1-fpm.conf ]; then
+    echo "/etc/apache2/conf-available/php7.1-fpm.conf not found" >&2
     exit 1
 fi
 
@@ -19,14 +19,14 @@ EOT
 # php-fpm here.
 a2dismod actions 2>/dev/null || true
 a2dismod cgi 2>/dev/null || true
-a2disconf php7.0-cgi 2>/dev/null || true
+a2disconf php7.1-cgi 2>/dev/null || true
 
 # Ensure that mod_php is disabled
-a2dismod php7.0 2>/dev/null || true
+a2dismod php7.1 2>/dev/null || true
 
 # php-fpm configuration requires mod_proxy_fcgi
 a2enmod proxy_fcgi 2>/dev/null || true
-a2enconf php7.0-fpm 2>/dev/null || true
+a2enconf php7.1-fpm 2>/dev/null || true
 service apache2 restart 2>/dev/null
 result=`wget -O- http://localhost/hello.php 2>/dev/null`
 test "$result" = "Hello, world!"
