Regenerate d/control and d/tests

diff --git a/debian/tests/fpm b/debian/tests/fpm
--- a/debian/tests/fpm
+++ b/debian/tests/fpm
@@ -4,22 +4,29 @@ set -e
 # PHP-FPM test based on mod-php test
 # Author: Neal Gompa <ngompa13@gmail.com>
 
+# /etc/apache2/conf-available/php5.6-fpm.conf should exist.
+
+if [ ! -f /etc/apache2/conf-available/php5.6-fpm.conf ]; then
+    echo "/etc/apache2/conf-available/php5.6-fpm.conf not found" >&2
+    exit 1
+fi
+
 cat > /var/www/html/hello.php <<EOT
 <?php echo "Hello, world!\n"; ?>
 EOT
 
-# Make sure that any CGI mechanism is disabled, since we want to test mod_php
-# mode here.
+# Make sure that any CGI mechanism is disabled, since we want to test
+# php-fpm here.
 a2dismod actions 2>/dev/null || true
 a2dismod cgi 2>/dev/null || true
 a2disconf php5.6-cgi 2>/dev/null || true
 
 # Ensure that mod_php is disabled
-a2dismod php5.6 2>/dev/null
+a2dismod php5.6 2>/dev/null || true
 
 # php-fpm configuration requires mod_proxy_fcgi
-a2enmod proxy_fcgi
-a2enconf php5.6-fpm
+a2enmod proxy_fcgi 2>/dev/null || true
+a2enconf php5.6-fpm 2>/dev/null || true
 service apache2 restart 2>/dev/null
 result=`wget -O- http://localhost/hello.php 2>/dev/null`
 test "$result" = "Hello, world!"
