Regenerate debian directory with php5.5

diff --git a/debian/tests/mod-php b/debian/tests/mod-php
--- a/debian/tests/mod-php
+++ b/debian/tests/mod-php
@@ -3,6 +3,20 @@ set -e
 
 # Author: Robie Basak <robie.basak@ubuntu.com>
 
+
+# /etc/apache2/mods-available/php5.5.{conf,load} should exist.
+
+if [ ! -f /etc/apache2/mods-available/php5.5.conf ]; then
+    echo "/etc/apache2/mods-available/php5.5.conf not found" >&2
+    exit 1
+fi
+
+if [ ! -f /etc/apache2/mods-available/php5.5.load ]; then
+    echo "/etc/apache2/mods-available/php5.5.load not found" >&2
+    exit 1
+fi
+
+
 cat > /var/www/html/hello.php <<EOT
 <?php echo "Hello, world!\n"; ?>
 EOT
@@ -13,7 +27,12 @@ a2dismod actions 2>/dev/null || true
 a2dismod cgi 2>/dev/null || true
 a2disconf php5.5-cgi 2>/dev/null || true
 
-a2enmod php5.5 2>/dev/null
+# Make sure that fpm configuration is disabled for the same reasons we disabled
+# CGI mechanisms
+a2dismod proxy_fcgi 2>/dev/null || true
+a2disconf php5.5-fpm 2>/dev/null || true
+
+a2enmod php5.5 2>/dev/null || true
 service apache2 restart 2>/dev/null
 result=`wget -O- http://localhost/hello.php 2>/dev/null`
 test "$result" = "Hello, world!"
